Assignment/Assignment/Models/DbModels.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModels : DbContext
    {
        public DbModels()
            : base("name=DbModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emp> Emp { get; set; }
    }
}

Assignment/Assignment/Models/DbModels.Designer.cs
// T4 code generation is enabled for model 'G:\ASP.Net\Assignment\Assignment\Models\DbModels.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Assignment/Assignment/Models/DbModels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Assignment/Assignment/Models/Emp.cs
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage ="this is required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "this is required")]

        public string LastName { get; set; }

        [Required(ErrorMessage = "this is required")]

        public System.DateTime Dob { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string Gender { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string EmpType { get; set; }
        [Required(ErrorMessage = "this is required")]

        public int Sal { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string Detp { get; set; }
        [Required(ErrorMessage = "this is required")]

        public string Email { get; set; }

    }
  
}

Assignment/Assignment/Models/employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace Assignment.Models
{
    public class employee
    {
        [Required(ErrorMessage = "Please Enter an ID!")]
        //[Display(Name = "Id")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Name!")]
        //[Display(Name = "Pr_Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Date!")]
        //[Display(Name = "Expire Date")]
        [DataType(DataType.Date)]
        public DateTime ExpireDob { get; set; }

        //[Display(Name = "Quantity")]
        public string Quantity { get; set; }

       // [Display(Name = "Price")]
        public int Price { get; set; }

    }
}

Assignment/Assignment/Controllers/ForhadEmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment.Models;

namespace Assignment.Controllers
{
    public class ForhadEmpController : Controller
    {
        // GET: ForhadEmp
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveData(employee idea)
        {
            if (idea != null)
            {
                return View();
            }
            return View("Index");
        }
    }
}

Assignment/Assignment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment.Models;

namespace Assignment.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult AddOrEdit(int id=0)
        {
            Emp empModel = new Emp();
            

            return View(empModel);
        }
        [HttpPost]
        public ActionResult AddOrEdit(Emp empModel)
        {
            using (DbModels dbModel = new DbModels())
            {
                dbModel.Emp.Add(empModel);
                dbModel.SaveChanges();

            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration Successfully Complete.";
            return View("AddOrEdit", new Emp());
        }

      //  public ActionResult About()
        //{
          //  ViewBag.Message = "Your application description page.";

            //return View();
        //}

        //public ActionResult Contact()
        //{
          //  ViewBag.Message = "Your contact page.";

            //return View();
        //}
    }
}

Assignment/Assignment/Views/ForhadEmp/Index.cshtml
@model  Assignment.Models.employee
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Product</title>
</head>
<body>
    <div>

        @*@Html.DisplayName("Id:") - @Html.Editor("Id")
        <br /><br />
        @Html.DisplayFor(x => x.Pr_Name) - @Html.EditorFor(x => x.Pr_Name)
        <br />
        <br />
        @Html.DisplayFor(x => x.Quantity) - @Html.EditorFor(x => x.Quantity)
        <br />
        <br />
        @Html.DisplayFor(x => x.ExpireDob) - @Html.EditorFor(x => x.ExpireDob)
        <br />
        <br />
        @Html.DisplayFor(x => x.Price) - @Html.EditorFor(x => x.Price)
        <hr />
        @Html.EditorForModel()*@


        @using (Html.BeginForm("SaveData", "ForhadEmp", FormMethod.Post))
        {

            <br />
        <br />
        @Html.Label("Product ID:")
        @Html.TextBox("Id")
        <br />
        @Html.ValidationMessage("Id")
        <br />
        @Html.Label("Product Name:")
        @Html.TextBox("Name")
        <br />
        @Html.ValidationMessage("Name")
        <br />
        @Html.Label("Product Price:")
        @Html.TextBox("Price")
        <br />
        @Html.ValidationMessage("Price")

        <br />
        @Html.Label("Product Quantity:")
        @Html.TextBox("Quantity")
        <br />
        @Html.ValidationMessage("Quantity")
        <br />
        <br />
        @Html.Label("ExpiteDate")
        @Html.DisplayFor(x => x.ExpireDob) @Html.EditorFor(x => x.ExpireDob)
        <br />
        <br />

        <input type="submit" value="Save" />
       
        }

    </div>
</body>
</html>

Assignment/Assignment/Views/ForhadEmp/SaveData.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SaveData</title>
</head>
<body>
    <div>
        <h3>Data Saved</h3>
    </div>
</body>
</html>